version: "3"

services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres:/var/lib/postgresql/data 
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
  server:
    image: node:19.0.0-alpine
    working_dir: /home/node
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start:dev"
    environment:
      - MONGO_URL=mongodb://db:27017/my-nest-db?authSource=admin
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=amin_secret 
    volumes:
      - ./server:/home/node
    depends_on:
      - db
      - postgres

volumes:
  db: {}
  postgres: {}
